# Generated by Django 2.1 on 2018-08-02 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_fname', models.CharField(max_length=50)),
                ('contact_lname', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254, null=True)),
                ('contact_username', models.CharField(max_length=50, null=True)),
                ('contact_phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DTContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtcontact_fname', models.CharField(max_length=50)),
                ('dtcontact_lname', models.CharField(max_length=50)),
                ('dtcontact_phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaturityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maturitymodel_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar_text', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField(null=True, verbose_name='date_started')),
                ('end_date', models.DateField(null=True, verbose_name='date_ended')),
                ('create_date', models.DateField()),
                ('alignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Alignment')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Contact')),
                ('keywords', models.ManyToManyField(to='projects.Keyword')),
                ('maturitymodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.MaturityModel')),
                ('pillar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Pillar')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Status')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField()),
                ('update_text', models.CharField(max_length=150)),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='tracker',
            name='updates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Update'),
        ),
    ]
