# Generated by Django 2.1 on 2018-08-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='pillar',
        ),
        migrations.DeleteModel(
            name='Pillar',
        ),
    ]
