# Generated by Django 2.1 on 2018-08-02 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180802_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='keywords',
            field=models.ManyToManyField(null=True, to='projects.Keyword'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='maturitymodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.MaturityModel'),
        ),
    ]
