# Generated by Django 2.1 on 2018-08-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180802_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='date_ended'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='projects.Keyword'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='date_started'),
        ),
    ]
