# Generated by Django 2.1 on 2018-08-02 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180802_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='updates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Update'),
        ),
    ]
