# Generated by Django 2.1 on 2018-08-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180802_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateField()),
                ('comment_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='updates',
        ),
        migrations.AddField(
            model_name='update',
            name='update_tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Tracker'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Tracker'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Contact'),
        ),
    ]
