# Generated by Django 2.1 on 2018-08-04 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180803_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_tracker',
        ),
        migrations.RemoveField(
            model_name='update',
            name='update_tracker',
        ),
        migrations.AddField(
            model_name='tracker',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Comment'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='updates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Update'),
        ),
    ]
