# Generated by Django 2.1 on 2018-08-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180804_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
