# Generated by Django 2.1 on 2018-08-14 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180809_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='updates',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Tracker'),
        ),
        migrations.AddField(
            model_name='update',
            name='update_tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Tracker'),
        ),
    ]
