# Generated by Django 2.1 on 2018-08-14 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180814_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='dtcontact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.DTContact'),
        ),
    ]
